services:
  postgres:
    image: postgres:latest
    container_name: finask_postgres
    environment:
      POSTGRES_USER: finask_user
      POSTGRES_PASSWORD: finask_password
      POSTGRES_DB: finask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: finask_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: